---
nodes:
  - hostname: infra
    box: 'centos/7'
    ip: '192.168.50.12'
    memory: '2048'
    vCPUs: '1'
  - hostname: compute
    box: 'centos/7'
    ip: '192.168.50.13'
    memory: '2048'
    vCPUs: '1'
  - hostname: master
    box: 'centos/7'
    ip: '192.168.50.11'
    memory: '2048'
    vCPUs: '1'
okd:
  domain: 'okd.local'
